spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/orcl
    username: system
    password: 1234
    driver-class-name: oracle.jdbc.driver.OracleDriver
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
mybatis:
  config-location: classpath:configuration.xml
  mapper-locations: classpath:mappers/*.xml